books/urls.py
from django.conf.urls import url

from . import views as books_views

app_name = 'books'

urlpatterns = [
    url(r'^search_by_title/$', books_views.search_by_title, name='search_by_title'),
    url(r'^search_by_valid_title/$', books_views.search_by_valid_title, name='search_by_valid_title'),
    url(r'^custom_filters/$', books_views.custom_filters, name='custom_filters'),
    url(r'^custom_tags/$', books_views.custom_tags, name='custom_tags'),
    url(r'^advanced_custom_tags/$', books_views.advanced_custom_tags, name='advanced_custom_tags'),
    url(r'^c2_related_objects/$', books_views.c2_related_objects, name='c2_related_objects'),
    url(r'^c2_model_manager/$', books_views.c2_model_manager, name='c2_model_manager'),
]

django_core_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from books import urls as books_urls
from django_core_project import settings
from . import views as project_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', project_views.index, name='index'),
    url(r'^hello/$', project_views.hello_world, name="hello_world"),
    url(r'^now/$', project_views.current_datetime, name="datetime_now"),
    url(r'^now/plus/(?P<hours_ahead>[\d]+)/$', project_views.ahead_datetime, name="datetime_ahead"),
    url(r'^request_meta/$', project_views.request_meta, name='request_meta'),
    url(r'^simple_form_handling/$', project_views.simple_form_handling, name='simple_form_handling'),
    url(r'^books/', include(books_urls)),
    url(r'^contact/$', project_views.contact_form, name='contact_form'),
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^debug/$', project_views.debug, name='debug'),
    ]

urlpatterns += [
    url(r'^', project_views.no_page, name="no_page"),
]

templates/partials/end_body_scripts.html
{% load staticfiles %}

<!-- jQuery -->
<script src="{% static "js/jquery.js" %}"></script>

<!-- Bootstrap Core JavaScript -->
<script src="{% static "js/bootstrap.js" %}"></script>

<!-- Metis Menu Plugin JavaScript -->
<script src="{% static "js/metisMenu.js" %}"></script>

<!-- Morris Charts JavaScript -->
<script src="{% static "js/raphael.js" %}"></script>
<script src="{% static "js/morris.js" %}"></script>
<script src="{% static "js/morris-data.js" %}"></script>

<!-- Custom Theme JavaScript -->
<script src="{% static "js/sb-admin-2.js" %}"></script>

templates/partials/footer.html
<!-- Footer -->
<div id="footer" class="container-fluid">
    <div class="container">
        <p>&copy; Adrian Pothuaud</p>
    </div>
</div>

templates/partials/head_stylesheets.html
{% load staticfiles %}
<!-- Bootstrap Core CSS -->
<link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">

<!-- MetisMenu CSS -->
<link href="{% static "css/metisMenu.css" %}" rel="stylesheet">

<!-- Custom CSS -->
<link href="{% static "css/sb-admin-2.css" %}" rel="stylesheet">

<!-- Morris Charts CSS -->
<link href="{% static "css/morris.css" %}" rel="stylesheet">

<!-- Custom Fonts -->
<link href="{% static "css/font-awesome.css" %}" rel="stylesheet" type="text/css">

<!-- specific styling -->
<link href="{% static "css/django_core.css" %}" rel="stylesheet" type="text/css">

templates/partials/navbar_right.html
<ul class="nav navbar-top-links navbar-right">
    {% comment %}
        <!-- Messages -->
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <i class="fa fa-envelope fa-fw"></i> <i class="fa fa-caret-down"></i>
            </a>
            <ul class="dropdown-menu dropdown-messages">
                <li>
                    <a href="#">
                        <div>
                            <strong>John Smith</strong>
                            <span class="pull-right text-muted">
                                <em>Yesterday</em>
                            </span>
                        </div>
                        <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <div>
                            <strong>John Smith</strong>
                            <span class="pull-right text-muted">
                                <em>Yesterday</em>
                            </span>
                        </div>
                        <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <div>
                            <strong>John Smith</strong>
                            <span class="pull-right text-muted">
                                <em>Yesterday</em>
                            </span>
                        </div>
                        <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a class="text-center" href="#">
                        <strong>Read All Messages</strong>
                        <i class="fa fa-angle-right"></i>
                    </a>
                </li>
            </ul>
            <!-- /.dropdown-messages -->
        </li>
        <!-- /.dropdown -->
        <!-- tasks -->
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <i class="fa fa-tasks fa-fw"></i> <i class="fa fa-caret-down"></i>
            </a>
            <ul class="dropdown-menu dropdown-tasks">
                <li>
                    <a href="#">
                        <div>
                            <p>
                                <strong>Task 1</strong>
                                <span class="pull-right text-muted">40% Complete</span>
                            </p>
                            <div class="progress progress-striped active">
                                <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%">
                                    <span class="sr-only">40% Complete (success)</span>
                                </div>
                            </div>
                        </div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <div>
                            <p>
                                <strong>Task 2</strong>
                                <span class="pull-right text-muted">20% Complete</span>
                            </p>
                            <div class="progress progress-striped active">
                                <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style="width: 20%">
                                    <span class="sr-only">20% Complete</span>
                                </div>
                            </div>
                        </div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <div>
                            <p>
                                <strong>Task 3</strong>
                                <span class="pull-right text-muted">60% Complete</span>
                            </p>
                            <div class="progress progress-striped active">
                                <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%">
                                    <span class="sr-only">60% Complete (warning)</span>
                                </div>
                            </div>
                        </div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <div>
                            <p>
                                <strong>Task 4</strong>
                                <span class="pull-right text-muted">80% Complete</span>
                            </p>
                            <div class="progress progress-striped active">
                                <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 80%">
                                    <span class="sr-only">80% Complete (danger)</span>
                                </div>
                            </div>
                        </div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a class="text-center" href="#">
                        <strong>See All Tasks</strong>
                        <i class="fa fa-angle-right"></i>
                    </a>
                </li>
            </ul>
            <!-- /.dropdown-tasks -->
        </li>
        <!-- /.dropdown -->
        <!-- Notifications -->
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <i class="fa fa-bell fa-fw"></i> <i class="fa fa-caret-down"></i>
            </a>
            <ul class="dropdown-menu dropdown-alerts">
                <li>
                    <a href="#">
                        <div>
                            <i class="fa fa-comment fa-fw"></i> New Comment
                            <span class="pull-right text-muted small">4 minutes ago</span>
                        </div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <div>
                            <i class="fa fa-twitter fa-fw"></i> 3 New Followers
                            <span class="pull-right text-muted small">12 minutes ago</span>
                        </div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <div>
                            <i class="fa fa-envelope fa-fw"></i> Message Sent
                            <span class="pull-right text-muted small">4 minutes ago</span>
                        </div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <div>
                            <i class="fa fa-tasks fa-fw"></i> New Task
                            <span class="pull-right text-muted small">4 minutes ago</span>
                        </div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <div>
                            <i class="fa fa-upload fa-fw"></i> Server Rebooted
                            <span class="pull-right text-muted small">4 minutes ago</span>
                        </div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a class="text-center" href="#">
                        <strong>See All Alerts</strong>
                        <i class="fa fa-angle-right"></i>
                    </a>
                </li>
            </ul>
            <!-- /.dropdown-alerts -->
        </li>
        <!-- /.dropdown -->
        <!-- User menu -->
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
            </a>
            <ul class="dropdown-menu dropdown-user">
                <li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
                </li>
                <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
                </li>
                <li class="divider"></li>
                <li><a href="login.html"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                </li>
            </ul>
            <!-- /.dropdown-user -->
        </li>
        <!-- /.dropdown -->
        {% endcomment %}
        {% if request.user.is_superuser %}
            <li><a href="/admin/"><i class="fa fa-cog fa-spin fa-fw"></i> Admin</a></li>
        {% endif %}
    </ul>
    <!-- /.navbar-top-links -->

templates/partials/sidebar.html
<!-- sidebar -->
    <div class="navbar-default sidebar" role="navigation">
        <div class="sidebar-nav navbar-collapse">
            <ul class="nav" id="side-menu">
                {% comment %}
                <li class="sidebar-search">
                    <div class="input-group custom-search-form">
                        <input type="text" class="form-control" placeholder="Search...">
                        <span class="input-group-btn">
                        <button class="btn btn-default" type="button">
                            <i class="fa fa-search"></i>
                        </button>
                    </span>
                    </div>
                    <!-- /input-group -->
                </li>
                {% endcomment %}
                <!-- /.nav-second-level -->
                <li><small class="text-warning text-muted"> Introductory</small></li>
                <li>
                    <a href="{% url 'hello_world' %}"><i class="fa fa-hand-peace-o"></i> HelloWorld</a>
                </li>
                <li>
                    <a href="#"><i class="fa fa-clock-o"></i> Date&Time<span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">
                        <li>
                            <a href="{% url 'datetime_now' %}">Present</a>
                        </li>
                        <li>
                            <a href="{% url 'datetime_ahead' 4 %}">Future</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="{% url 'request_meta' %}"><i class="fa fa-user-secret"></i> Request Info</a>
                </li>
                <li>
                    <a><i class="fa fa-check-square-o"></i> Forms<span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">
                        <li><a href="{% url 'simple_form_handling' %}"><i class="fa fa-search"></i> 1. Simple search</a></li>
                        <li><a href="{% url 'books:search_by_title' %}"><i class="fa fa-book"></i> 2. Search Books</a></li>
                        <li><a href="{% url 'books:search_by_valid_title' %}"><i class="fa fa-code"></i> 3. Simple validation</a></li>
                        <li><a href="{% url 'contact_form' %}"><i class="fa fa-envelope"></i> 4. Contact Form</a></li>
                    </ul>
                </li>
                <li><small class="text-warning text-muted"> Advanced</small></li>
                <li><a href="{% url 'debug' %}"><i class="fa fa-delicious"></i> Debug view</a></li>
                <li>
                    <a><i class="fa fa-tag"></i> Templating<span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">
                        <li><a href="{% url 'books:custom_filters' %}"><i class="fa fa-filter"></i> Custom filters</a></li>
                        <li><a href="{% url 'books:custom_tags' %}"><i class="fa fa-tag"></i> Custom tags</a></li>
                        <li><a href="#"><i class="fa fa-tag"></i> Advanced custom tags</a></li>
                    </ul>
                </li>
                <li>
                    <a><i class="fa fa-database"></i> Models<span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">
                        <li><a href="{% url 'books:c2_related_objects' %}"><i class="fa fa-link"></i> Related objects</a></li>
                        <li><a href="{% url 'books:c2_model_manager' %}"><i class="fa fa-magic"></i> Model manager</a></li>
                    </ul>
                </li>
                {% comment %}
                <li>
                    <a href="index.html"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
                </li>
                <li>
                    <a href="#"><i class="fa fa-bar-chart-o fa-fw"></i> Charts<span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">
                        <li>
                            <a href="flot.html">Flot Charts</a>
                        </li>
                        <li>
                            <a href="morris.html">Morris.js Charts</a>
                        </li>
                    </ul>
                    <!-- /.nav-second-level -->
                </li>
                <li>
                    <a href="tables.html"><i class="fa fa-table fa-fw"></i> Tables</a>
                </li>
                <li>
                    <a href="forms.html"><i class="fa fa-edit fa-fw"></i> Forms</a>
                </li>
                <li>
                    <a href="#"><i class="fa fa-wrench fa-fw"></i> UI Elements<span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">
                        <li>
                            <a href="panels-wells.html">Panels and Wells</a>
                        </li>
                        <li>
                            <a href="buttons.html">Buttons</a>
                        </li>
                        <li>
                            <a href="notifications.html">Notifications</a>
                        </li>
                        <li>
                            <a href="typography.html">Typography</a>
                        </li>
                        <li>
                            <a href="icons.html"> Icons</a>
                        </li>
                        <li>
                            <a href="grid.html">Grid</a>
                        </li>
                    </ul>
                    <!-- /.nav-second-level -->
                </li>
                <li>
                    <a href="#"><i class="fa fa-sitemap fa-fw"></i> Multi-Level Dropdown<span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">
                        <li>
                            <a href="#">Second Level Item</a>
                        </li>
                        <li>
                            <a href="#">Second Level Item</a>
                        </li>
                        <li>
                            <a href="#">Third Level <span class="fa arrow"></span></a>
                            <ul class="nav nav-third-level">
                                <li>
                                    <a href="#">Third Level Item</a>
                                </li>
                                <li>
                                    <a href="#">Third Level Item</a>
                                </li>
                                <li>
                                    <a href="#">Third Level Item</a>
                                </li>
                                <li>
                                    <a href="#">Third Level Item</a>
                                </li>
                            </ul>
                            <!-- /.nav-third-level -->
                        </li>
                    </ul>
                    <!-- /.nav-second-level -->
                </li>
                <li>
                    <a href="#"><i class="fa fa-files-o fa-fw"></i> Sample Pages<span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">
                        <li>
                            <a href="blank.html">Blank Page</a>
                        </li>
                        <li>
                            <a href="login.html">Login Page</a>
                        </li>
                    </ul>
                    <!-- /.nav-second-level -->
                </li>
                {% endcomment %}
            </ul>
        </div>
        <!-- /.sidebar-collapse -->
    </div>
<!-- /.navbar-static-side -->