books/urls.py
from django.conf.urls import url

from . import views as books_views

app_name = 'books'

urlpatterns = [
    url(r'^search_by_title/$', books_views.search_by_title, name='search_by_title'),
    url(r'^search_by_valid_title/$', books_views.search_by_valid_title, name='search_by_valid_title'),
    url(r'^custom_filters/$', books_views.custom_filters, name='custom_filters'),
    url(r'^custom_tags/$', books_views.custom_tags, name='custom_tags'),
    url(r'^advanced_custom_tags/$', books_views.advanced_custom_tags, name='advanced_custom_tags'),
    url(r'^c2_related_objects/$', books_views.c2_related_objects, name='c2_related_objects'),
    url(r'^c2_model_manager/$', books_views.c2_model_manager, name='c2_model_manager'),
]

django_core_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from books import urls as books_urls
from django_core_project import settings
from . import views as project_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', project_views.index, name='index'),
    url(r'^hello/$', project_views.hello_world, name="hello_world"),
    url(r'^now/$', project_views.current_datetime, name="datetime_now"),
    url(r'^now/plus/(?P<hours_ahead>[\d]+)/$', project_views.ahead_datetime, name="datetime_ahead"),
    url(r'^request_meta/$', project_views.request_meta, name='request_meta'),
    url(r'^simple_form_handling/$', project_views.simple_form_handling, name='simple_form_handling'),
    url(r'^books/', include(books_urls)),
    url(r'^contact/$', project_views.contact_form, name='contact_form'),
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^debug/$', project_views.debug, name='debug'),
    ]

urlpatterns += [
    url(r'^', project_views.no_page, name="no_page"),
]

books/models.py
from django.db import models


# Create your models here.


class Publisher(models.Model):
    name = models.CharField(max_length=30)
    address = models.CharField(max_length=50)
    city = models.CharField(max_length=60)
    state_province = models.CharField(max_length=30)
    country = models.CharField(max_length=50)
    website = models.URLField()

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']


class Author(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=40)
    email = models.EmailField(blank=True, verbose_name='e-mail')

    def __str__(self):
        return u'%s %s' % (self.first_name, self.last_name)

    class Meta:
        ordering = ['first_name', 'last_name']


class BookManager(models.Manager):
    def title_count(self, keyword):
        # returns the number of books that title contains the given keyword
        return self.filter(title__icontains=keyword).count()


class AlbertBookManager(models.Manager):
    def get_queryset(self):
        return super(AlbertBookManager,
                     self).get_queryset().filter(authors__last_name__contains='Einstein')


class Book(models.Model):
    title = models.CharField(max_length=100)
    authors = models.ManyToManyField(Author)
    publisher = models.ForeignKey(Publisher)
    publication_date = models.DateField(blank=True, null=True)
    num_pages = models.IntegerField(blank=True, null=True)
    objects = BookManager()
    albert_objects = AlbertBookManager()

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['title']

books/views.py
import sys

from django.shortcuts import render

# Create your views here.
from books.models import Book

sys.stdout = sys.stderr


def search_by_title(request):
    results = None
    if 'q' in request.GET and request.GET['q']:
        # form with request method have been submitted
        results = Book.objects.filter(title__icontains=request.GET['q'])
    if 'q' in request.POST and request.POST['q']:
        # form with post method have been submitted
        results = Book.objects.filter(title__icontains=request.POST['q'])
    return render(request, 'books/search_by_title.html', context={'results': results})


def search_by_valid_title(request):
    results = None
    get_method_errors = []
    post_method_errors = []

    print(request.GET)
    print(request.POST)

    if request.method == 'GET':
        # form with request method have been submitted

        try:
            q = request.GET['q']

            if not q:
                get_method_errors.append({
                    'abstract': 'Empty Query',
                    'message': 'You\'ve entered an empty search query ... Search query should not be empty!',
                    'instructions': 'Please enter a query not empty for your next try.'
                })

            elif len(q) > 20:
                get_method_errors.append({
                    'abstract': 'Too Long Query',
                    'message': 'You\'ve entered {}, this query is {} chars long ... '
                               'Search query should not be longer than 20 chars!'.format(q, len(q)),
                    'instructions': 'Please enter a shorter query.'
                })

            else:
                results = Book.objects.filter(title__icontains=request.GET['q'])

        except KeyError:
            pass

    if request.method == 'POST':
        # form with post method have been submitted

        try:
            q = request.POST['q']

            if not q:
                post_method_errors.append({
                    'abstract': 'Empty Query',
                    'message': 'You\'ve entered an empty search query ... Search query should not be empty!',
                    'instructions': 'Please enter a query not empty for your next try.'
                })

            elif len(q) > 20:
                post_method_errors.append({
                    'abstract': 'Too Long Query',
                    'message': 'You\'ve entered {}, this query is {} chars long ... '
                               'Search query should not be longer than 20 chars!'.format(q, len(q)),
                    'instructions': 'Please enter a shorter query.'
                })

            else:
                results = Book.objects.filter(title__icontains=request.POST['q'])

        except KeyError:
            pass

    context_dic = {
        'results': results,
        'get_method_errors': get_method_errors,
        'post_method_errors': post_method_errors
    }
    print(context_dic)

    return render(request, 'books/search_by_title_with_validation.html', context=context_dic)


def custom_filters(request):
    return render(request, template_name='books/custom_filters.html', context={
        'test_chars': 'UAOIUZKVNZLDJVO',
    })


def custom_tags(request):
    return render(request, template_name='books/custom_tags.html', context=None)


def advanced_custom_tags(request):
    return render(request, template_name='books/advanced_custom_tags.html', context=None)


def c2_related_objects(request):
    first_book = Book.objects.first()
    return render(request, template_name='books/c2_related_objects.html', context={
        'first_book': first_book,
    })


def c2_model_manager(request):
    title_count = None
    search_form_error = None
    query_placeholder = "Search"
    albert_books = Book.albert_objects.all()
    if request.method == 'POST':
        keyword = request.POST['keyword']
        if not keyword:
            search_form_error = "Empty search query."
        elif len(keyword) > 20:
            search_form_error = "Too long query."
        else:
            query_placeholder = keyword
            title_count = Book.objects.title_count(keyword)
    return render(request, 'books/c2_model_manager.html', {
        'title_count': title_count,
        'search_form_error': search_form_error,
        'query_placeholder': query_placeholder,
        'albert_books': albert_books,
    })

templates/books/advanced_custom_tags.html
{% extends 'base.html' %}

{% block page_title %}
    Tags
{% endblock %}

{% block title %}
    Django Core
{% endblock %}

{% block navbar_title %}
    Custom Tags
{% endblock %}

{% block content_title %}
    Advanced Custom Template tags
{% endblock %}

{% block content %}
    <h5>Below is usage of advanced custom template tag example</h5>

    <p>{% adv_current_time "%A %d %B %-Hh%M" %}</p>

{% endblock %}

templates/books/books.html
<ul>
{% for book in books %}
    <li> {{ book }} </li>
{% endfor %}
</ul>

templates/books/c2_model_manager.html
{% extends 'base.html' %}

{% block page_title %}
    Models
{% endblock %}

{% block title %}
    Django Core
{% endblock %}

{% block navbar_title %}
    Model Manager
{% endblock %}

{% block content_title %}
    Advanced Django Model
{% endblock %}

{% block content %}

    <div class="row">
        <blockquote class="quote-box">
          <p class="quotation-mark">
            “
          </p>
          <p class="quote-text text-muted">
            In short, a model’s manager is an object through which Django models perform database queries.
              Each Django model has at least one manager, and you can create custom managers in order to customize database access.
              There are two reasons you might want to create a custom manager: to add extra manager methods,
              and/or to modify the initial QuerySet the manager returns.
          </p>
          <hr>
          <div class="blog-post-actions">
            <p class="blog-post-bottom pull-left">
              Nigel George. “Mastering Django: Core.”
            </p>
          </div>
        </blockquote>
    </div>

    <div class="row">
        <h4>BookManager.title_count</h4>
        <p class="text-info">Enter a keyword and the BookManager will return the number of book titles containing it.</p>
        <p>View code is like : </p>
        <p><code>title_count = Book.objects.title_count(keyword)</code></p>
        {% if title_count is None %}
            <p class="text-primary">Enter your query below ...</p>
        {% endif %}
        <form method="post" action="." class="form-inline input-group col-xs-12 col-md-4">
            {% csrf_token %}
            {% if search_form_error %}
                <p class="alert-danger text-center">{{ search_form_error }}</p>
            {% endif %}
            <input type="text" name="keyword" placeholder="{{ query_placeholder }}" />
            &nbsp;&nbsp;
            <button class="btn-danger" type="submit">
                <i class="fa fa-search"></i>
            </button>
        </form>
    </div>

    {% if title_count is not None %}
        <div class="row">
            <h5>Result :</h5>
            <p class="text-success">title_count = {{ title_count }}</p>
        </div>
    {% endif %}

    <hr/>


    <div class="row">
        <blockquote class="quote-box">
          <p class="quotation-mark">
            “
          </p>
          <p class="quote-text text-muted">
            A manager’s base QuerySet returns all objects in the system.
              For example, Book.objects.all() returns all books in the book database.
              You can override a manager’s base QuerySet by overriding the Manager.get_queryset() method.
              get_queryset() should return a QuerySet with the properties you require.
          </p>
          <hr>
          <div class="blog-post-actions">
            <p class="blog-post-bottom pull-left">
              Nigel George. “Mastering Django: Core.”
            </p>
          </div>
        </blockquote>
    </div>

    <div class="row">
        <h4>AlbertBookManager</h4>
        <p>View code is like : </p>
        <p><code>albert_books = Book.albert_objects.all()</code></p>
        <p>{{ albert_books }}</p>
    </div>

    <hr/>

    <div class="row">
        <blockquote class="quote-box">
          <p class="quotation-mark">
            “
          </p>
          <p class="quote-text text-muted">
            “Define custom methods on a model to add custom row-level functionality to your objects.
              Whereas managers are intended to do table-wide things, model methods should act on a particular model instance.
              This is a valuable technique for keeping business logic in one place - the model.
          </p>
          <hr>
          <div class="blog-post-actions">
            <p class="blog-post-bottom pull-left">
              Nigel George. “Mastering Django: Core.”
            </p>
          </div>
        </blockquote>
    </div>

    <div class="row">

    </div>

{% endblock %}

templates/books/c2_related_objects.html
{% extends 'base.html' %}

{% block page_title %}
    Models
{% endblock %}

{% block title %}
    Django Core
{% endblock %}

{% block navbar_title %}
    Django Models
{% endblock %}

{% block content_title %}
    Related Objects
{% endblock %}

{% block content %}

    <p>Book : {{ first_book }}</p>

    <h4>Accessing foreign key field</h4>

    <p>Publisher : {{ first_book.publisher }}</p>

    <h6>Reversed</h6>

    <p>Book : {{ first_book.publisher.book_set.first }}</p>

    <h4>Accessing many to many values</h4>

    <p>Authors : {{ first_book.authors.all }}</p>

    <h6>Reversed</h6>

    <p>Book : {{ first_book.authors.all.first.book_set.first }}</p>

{% endblock %}

templates/books/custom_filters.html
{% extends 'base.html' %}

{% block page_title %}
    Filters
{% endblock %}

{% block title %}
    Django Core
{% endblock %}

{% block navbar_title %}
    Custom Filters
{% endblock %}

{% block content_title %}
    Custom Template filters
{% endblock %}

{% block content %}
    <h5>Below are basic custom template filters examples</h5>
    {% load custom_filters_1 %}
    <p>{{ test_chars|lower }}</p>
    <p>{{ test_chars|better }}</p>
    <p>{{ test_chars|add_xxx }}</p>
{% endblock %}

templates/books/custom_tags.html
{% extends 'base.html' %}

{% block page_title %}
    Tags
{% endblock %}

{% block title %}
    Django Core
{% endblock %}

{% block navbar_title %}
    Custom Tags
{% endblock %}

{% block content_title %}
    Custom Template tags
{% endblock %}

{% block content %}
    <h5>Below are basic custom template tags examples</h5>
    <p class="text-info">simple tag</p>
    {% load custom_tags_1 %}
    <p><code>{{ "{% current_time '%A %d %B %-Hh%M' %}" }}</code></p>
    <p>{% current_time "%A %d %B %-Hh%M" %}</p>
    <p class="text-info">inclusion tag</p>
    <p><code>{{ "{% show_books %}" }}</code></p>
    {% show_books %}
    <p class="text-info">assignment tag</p>
    <p><code>{{ "{% show_users as users %}" }}</code></p>
    {% show_users as users %}
    {{ users }}
{% endblock %}

templates/books/search_by_title.html
{% extends 'base.html' %}

{% block page_title %}
    Books
{% endblock %}

{% block title %}
    Django Core
{% endblock %}

{% block navbar_title %}
    Search Books
{% endblock %}

{% block content_title %}
    Search Books by title
{% endblock %}

{% block content %}
    <p class="text-info">GET method</p>
    <form action="" method="get">
        <input type="text" name="q">
        <input class="btn btn-success" type="submit" value="Submit">
    </form>
    <p>Once submitted the current view will receive request parameters</p>
    <p>and the results list will be updated with books that title contains the given query</p>
    <p>Current url : {{ request.get_full_path }}</p>
    <p class="text-info">POST method</p>
    <form action="" method="post">
        {% csrf_token %}
        <input type="text" name="q">
        <input class="btn btn-success" type="submit" value="Submit">
    </form>
    <p>Once submitted the current view will receive post parameters</p>
    <p>and the results list will be updated with books that title contains the given query</p>
    <p>Current POST params : {{ request.POST }}</p>
    <a href="{% url 'books:search_by_title' %}" class="btn btn-primary">Refresh this page</a>

    <h3>Results</h3>
    {% if results %}
        <p>Found {{ results|length }} book{{ results|pluralize }}.</p>
        {% for result in results %}
            <p class="text-primary">{{ result }}</p>
        {% endfor %}
    {% else %}
        <p class="text-info">There is no results to be displayed.</p>
    {% endif %}
{% endblock %}

templates/books/search_by_title_with_validation.html
{% extends 'base.html' %}

{% block page_title %}
    Books
{% endblock %}

{% block title %}
    Django Core
{% endblock %}

{% block navbar_title %}
    Search Books
{% endblock %}

{% block content_title %}
    Search Books by title
{% endblock %}

{% block content %}

    <p class="text-warning"><strong>Try to run these queries with either an empty query or a long query...</strong></p>

    <p class="text-info">GET method</p>

    {% if get_method_errors %}
        <div class="row">
            {% for error in get_method_errors %}
                <div class="col-xs-12 col-md-6 col-lg-4 col-xl-3">
                    <div class="panel panel-danger">
                        <div class="panel-heading">
                            {{ error.abstract }}
                        </div>
                        <div class="panel-body">
                            <p class="text-danger">
                                {{ error.message }}
                            </p>
                        </div>
                        <div class="panel-footer">
                            <p class="text-info">{{ error.instructions }}</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% endif %}

    <form action="" method="get">
        <input type="text" name="q">
        <input class="btn btn-success" type="submit" value="Submit">
    </form>

    <p>Once submitted the current view will receive request parameters</p>
    <p>and the results list will be updated with books that title contains the given query</p>
    <p>Current url : {{ request.get_full_path }}</p>



    <p class="text-info">POST method</p>

    {% if post_method_errors %}
        <div class="row">
            {% for error in post_method_errors %}
                <div class="col-xs-12 col-md-6 col-lg-4 col-xl-3">
                    <div class="panel panel-danger">
                        <div class="panel-heading">
                            {{ error.abstract }}
                        </div>
                        <div class="panel-body">
                            <p class="text-danger">
                                {{ error.message }}
                            </p>
                        </div>
                        <div class="panel-footer">
                            <p class="text-info">{{ error.instructions }}</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% endif %}

    <form action="" method="post">
        {% csrf_token %}
        <input type="text" name="q">
        <input class="btn btn-success" type="submit" value="Submit">
    </form>

    <p>Once submitted the current view will receive post parameters</p>
    <p>and the results list will be updated with books that title contains the given query</p>
    <p>Current POST params : {{ request.POST }}</p>
    <a href="{% url 'books:search_by_valid_title' %}" class="btn btn-primary">Refresh this page</a>



    <h3>Results</h3>
    {% if results %}
        <p>Found {{ results|length }} book{{ results|pluralize }}.</p>
        {% for result in results %}
            <p class="text-primary">{{ result }}</p>
        {% endfor %}
    {% else %}
        <p class="text-info">There is no results to be displayed.</p>
    {% endif %}

{% endblock %}